#! /home/user/.rbenv/shims/ruby

require "pg"

def display_help
  puts <<~HELP

    An expense recording system

    Commands:
    -------------------------------------------------------
    add AMOUNT MEMO [DATE] - record a new expense

    clear - delete all expenses

    list - list all expenses

    delete NUMBER - remove expense with id NUMBER

    search QUERY - list expenses with a matching memo field
    -------------------------------------------------------
    HELP
end

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: "expenses")
  end

  def display_expenses
    result = @connection.exec "SELECT * FROM expenses ORDER BY created_on;"

    result.each do |row|
      puts [ row["id"].rjust(3),
             row["created_on"].rjust(10),
             row["amount"].rjust(12),
             row["memo"] ].join(' | ')
    end
  end

  def add_expense(amount, memo)
    sql = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, now());"
    @connection.exec_params(sql, [amount, memo])
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(args)
    command = args[0]
    case command
    when "list"
      @application.display_expenses
    when "add"
      abort "You must provide an amount and memo." unless args.size >= 3
      @application.add_expense(args[1].to_f, args[2])
    else
      display_help
    end
  end
end


CLI.new.run(ARGV)
